require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.nvimtree"
-- require "user.bufferline"
require "user.comment"
require "user.lualine"
require "user.toggleterm"
require "user.indentline"
-- require "user.alpha"
require "user.luasnip"
require "user.dap"
require "user.illuminate"
require "user.impatient"
require "user.autocommands"
-- require "user.navic"
-- require "user.winbar"
require "user.jabs"
require "user.diffview"
require "user.navigator"
